//Placeholders 2.1.1
#define VERSION_MAJOR 2
#define VERSION_MINOR 1
#define VERSION_PATCH 0
#define VERSION_STRING L"2.1.1"

//SystemMenu
#define SC_ABOUT 0x0010
#define SC_VERSION 0x0020
#define SC_CREATOR 0x0030

//StringTable
#define APP_TITLE 101
#define UNSUPPORTED_VERSION 102
#define TEXT_BODY 103
#define BETTERWINVER_ABOUT 104
#define BETTERWINVER_VERSION 105
#define BETTERWINVER_CREATOR 106
